
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-05T18:13:30-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "f247a1e5d57c6b5577f5103345d5b98031dc01f2",
 "version": "v0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
