# Generated by Django 3.0.6 on 2020-06-23 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, default=None, null=True, verbose_name='kezdet')),
                ('end', models.DateField(blank=True, default=None, null=True, verbose_name='vég')),
                ('salary', models.IntegerField(verbose_name='munkabér')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='labor.Employment', verbose_name='munkavállaló')),
            ],
            options={
                'verbose_name': 'bér',
                'verbose_name_plural': 'bérek',
                'db_table': 'salaries',
                'ordering': ['-begin'],
            },
        ),
    ]
