# Generated by Django 3.0.6 on 2020-06-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20200624_0515'),
        ('labor', '0009_payroll_timesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetstatistic',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='labor.TimeSheet', verbose_name='jelenléti'),
        ),
        migrations.CreateModel(
            name='AbsenseStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DurationField(blank=True, default=None, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='masterdata.PauseCategory', verbose_name='kategória')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absenses', to='labor.TimeSheet', verbose_name='jelenléti')),
            ],
        ),
    ]
