# Generated by Django 3.0.6 on 2020-06-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20200624_0515'),
        ('labor', '0010_auto_20200625_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetstatistic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='masterdata.TimeSheetCategory', verbose_name='kategória'),
        ),
    ]
