# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"OpenHSI": "01_capture.ipynb",
         "save": "02_convert.ipynb"}

modules = ["core.py"]

doc_url = "https://YiweiMao.github.io/openhsi/"

git_url = "https://github.com/YiweiMao/openhsi/tree/master/"

def custom_doc_links(name): return None
