[tool.poetry]
name = "starlette-graphene3"
version = "0.1.1"
description = "Use Graphene v3 on Starlette"
authors = ["Taku Fukada <naninunenor@gmail.com>"]
license = "MIT"
homepage = "https://github.com/ciscorn/starlette-graphene3"
repository = "https://github.com/ciscorn/starlette-graphene3"
keywords = ["graphene", "graphql"]
readme = "README.md"
classifiers = [
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet :: WWW/HTTP",
]

[tool.poetry.dependencies]
python = "^3.6.1"
graphene = ">=3.0b"
starlette = "^0.13.3"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
graphene-file-upload = "^1.2.2"
mypy = "^0.782"
pre-commit = "^2.2.0"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
python-multipart = "^0.0.5"
requests = "^2.24.0"
uvicorn = "^0.11.3"

[tool.isort]
include_trailing_comma = true
line_length=88
multi_line_output=3
known_third_party = ["graphene", "graphene_file_upload", "graphql", "pytest", "starlette"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
