[tool.poetry]
name = "mhealthlab-client"
version = "0.4.8"
description = "Client to download and decrypt data for lab projects of mhealthgroup.org"
authors = ["Qu Tang <tang.q@northeastern.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
paramiko = "^2.7.1"
progress = "^1.5"
pyzipper = "^0.3.1"
arus = "^1.1.2"
outdated = "^0.2.0"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.2"
pytest = "^5.4.3"

[tool.poetry.scripts]
mhlab = 'mhealthlab_client.mhlab:mhlab'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
