[tool.poetry]
name = "bas-web-map-inventory"
version = "0.4.0"
license = "OGL-UK-3.0"
description = "Inventory of geospatial layers and web maps provided by the BAS Mapping and Geographic Information Centre (MAGIC), visualised in Airtable."
authors = [
    "Felix Fennell <felnne@bas.ac.uk>"
]
readme = "README.md"
homepage = "https://github.com/antarctica/web-map-inventory"
repository = "https://github.com/antarctica/web-map-inventory"
classifiers = [
    "Framework :: Flask",
    "Development Status :: 3 - Alpha",
    "License :: Other/Proprietary License",
    "Intended Audience :: Science/Research"
]

packages = [
    {include = "bas_web_map_inventory"},
    {include = "tests", format = "sdist"},
]
include = [
    "bas_web_map_inventory/resources/json_schemas/*.json",
    "bas_web_map_inventory/resources/xml_schemas/*.xsd"
]

[tool.poetry.dependencies]
python = "^3.8"
airtable-python-wrapper = "^0.12.0"
Flask = "^1.1.1"
geoserver-restconfig = "1.0.2"
inquirer = "^2.6.3"
jsonschema = "^3.2.0"
lxml = "4.5.0"
OWSlib = "^0.19.0"
python-dotenv = "^0.10.3"
sentry-sdk = {version = "^0.13.5", extras = ["flask"]}
str2bool = "^1.1"
ulid-py = "^0.0.12"
# OWSlib dependencies - to pin version of indirect dependencies
pyproj = "2.6.0"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
pytest = "^5.3.2"
pytest-cov = "^2.8.1"
pytest-flask = "^0.15.0"
pytest-random-order = "^1.0.4"
tomlkit = "^0.5.8"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = ''

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
