
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-07T10:30:42-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e4daf8eda0c7573e9f2152f1c9050b719c61315",
 "version": "1.5.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
