
'''
This file is automatically generated; Do not edit it. :)
'''
VERSION_INFO = {
    'final': True,
    'version': '1.22.8.post1',
    'branch_nick': '(HEAD',
    'revision_id': 'b6ba135cc2bf0e5c95877912858eb6c916168137',
    'revno': 9604
}
