[tool.poetry]
name = "django-shopify-abandoned-checkout"
version = "0.0.8"
description = "Send Shopify abandoned checkout emails from Django"
authors = ["David Burke <dburke@thelabnyc.com>"]
license = "Apache License"
homepage = "https://gitlab.com/thelabnyc/django-shopify-abandoned-checkout"
repository = "https://gitlab.com/thelabnyc/django-shopify-abandoned-checkout"
keywords = ["django", "shopify"]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    'Environment :: Web Environment',
    'Framework :: Django',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Intended Audience :: Developers',
    "License :: OSI Approved :: Apache Software License",
]
packages = [
  {include = "shopify_abandoned_checkout"}
]

[tool.poetry.dependencies]
python = "^3.7"
Django = ">=2.2.0"
django-shopify-sync = "^2.2.0"

[tool.poetry.dev-dependencies]
celery = {version = "4.3.0", extras = ["redis"]}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
