# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import volume_pb2 as volume__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='apiserver.v2',
  syntax='proto3',
  serialized_options=b'Z-git.supremind.info/products/atom/proto/go/api',
  serialized_pb=b'\n\x0finference.proto\x12\x0c\x61piserver.v2\x1a\x0cvolume.proto\"\x8e\x01\n\x15\x41nalyzerInferenceSpec\x12+\n\x06models\x18\x01 \x03(\x0b\x32\x1b.apiserver.v2.VolumePathRef\x12\x30\n\x06inputs\x18\x02 \x03(\x0b\x32 .apiserver.v2.VideoAnalyzerInput\x12\x16\n\x0e\x61nalyzerConfig\x18\x03 \x01(\t\"S\n\x12VideoAnalyzerInput\x12*\n\x05video\x18\x01 \x01(\x0b\x32\x1b.apiserver.v2.VolumePathRef\x12\x11\n\tviolation\x18\x02 \x01(\t\"L\n\x17\x41nalyzerInferenceStatus\x12\x31\n\x06output\x18\x01 \x01(\x0b\x32!.apiserver.v2.VideoAnalyzerOutput\"|\n\x13VideoAnalyzerOutput\x12\x31\n\x06videos\x18\x01 \x03(\x0b\x32!.apiserver.v2.AnalyzerOutputVideo\x12\x32\n\x06\x65vents\x18\x02 \x03(\x0b\x32\".apiserver.v2.AnalyzerOutputEvents\"\"\n\x13\x41nalyzerOutputVideo\x12\x0b\n\x03url\x18\x01 \x01(\t\"#\n\x14\x41nalyzerOutputEvents\x12\x0b\n\x03url\x18\x01 \x01(\tB/Z-git.supremind.info/products/atom/proto/go/apib\x06proto3'
  ,
  dependencies=[volume__pb2.DESCRIPTOR,])




_ANALYZERINFERENCESPEC = _descriptor.Descriptor(
  name='AnalyzerInferenceSpec',
  full_name='apiserver.v2.AnalyzerInferenceSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='models', full_name='apiserver.v2.AnalyzerInferenceSpec.models', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='apiserver.v2.AnalyzerInferenceSpec.inputs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='analyzerConfig', full_name='apiserver.v2.AnalyzerInferenceSpec.analyzerConfig', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=190,
)


_VIDEOANALYZERINPUT = _descriptor.Descriptor(
  name='VideoAnalyzerInput',
  full_name='apiserver.v2.VideoAnalyzerInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='video', full_name='apiserver.v2.VideoAnalyzerInput.video', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='violation', full_name='apiserver.v2.VideoAnalyzerInput.violation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=275,
)


_ANALYZERINFERENCESTATUS = _descriptor.Descriptor(
  name='AnalyzerInferenceStatus',
  full_name='apiserver.v2.AnalyzerInferenceStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='apiserver.v2.AnalyzerInferenceStatus.output', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=353,
)


_VIDEOANALYZEROUTPUT = _descriptor.Descriptor(
  name='VideoAnalyzerOutput',
  full_name='apiserver.v2.VideoAnalyzerOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videos', full_name='apiserver.v2.VideoAnalyzerOutput.videos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='events', full_name='apiserver.v2.VideoAnalyzerOutput.events', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=479,
)


_ANALYZEROUTPUTVIDEO = _descriptor.Descriptor(
  name='AnalyzerOutputVideo',
  full_name='apiserver.v2.AnalyzerOutputVideo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='apiserver.v2.AnalyzerOutputVideo.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=515,
)


_ANALYZEROUTPUTEVENTS = _descriptor.Descriptor(
  name='AnalyzerOutputEvents',
  full_name='apiserver.v2.AnalyzerOutputEvents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='apiserver.v2.AnalyzerOutputEvents.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=552,
)

_ANALYZERINFERENCESPEC.fields_by_name['models'].message_type = volume__pb2._VOLUMEPATHREF
_ANALYZERINFERENCESPEC.fields_by_name['inputs'].message_type = _VIDEOANALYZERINPUT
_VIDEOANALYZERINPUT.fields_by_name['video'].message_type = volume__pb2._VOLUMEPATHREF
_ANALYZERINFERENCESTATUS.fields_by_name['output'].message_type = _VIDEOANALYZEROUTPUT
_VIDEOANALYZEROUTPUT.fields_by_name['videos'].message_type = _ANALYZEROUTPUTVIDEO
_VIDEOANALYZEROUTPUT.fields_by_name['events'].message_type = _ANALYZEROUTPUTEVENTS
DESCRIPTOR.message_types_by_name['AnalyzerInferenceSpec'] = _ANALYZERINFERENCESPEC
DESCRIPTOR.message_types_by_name['VideoAnalyzerInput'] = _VIDEOANALYZERINPUT
DESCRIPTOR.message_types_by_name['AnalyzerInferenceStatus'] = _ANALYZERINFERENCESTATUS
DESCRIPTOR.message_types_by_name['VideoAnalyzerOutput'] = _VIDEOANALYZEROUTPUT
DESCRIPTOR.message_types_by_name['AnalyzerOutputVideo'] = _ANALYZEROUTPUTVIDEO
DESCRIPTOR.message_types_by_name['AnalyzerOutputEvents'] = _ANALYZEROUTPUTEVENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnalyzerInferenceSpec = _reflection.GeneratedProtocolMessageType('AnalyzerInferenceSpec', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZERINFERENCESPEC,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.AnalyzerInferenceSpec)
  })
_sym_db.RegisterMessage(AnalyzerInferenceSpec)

VideoAnalyzerInput = _reflection.GeneratedProtocolMessageType('VideoAnalyzerInput', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOANALYZERINPUT,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.VideoAnalyzerInput)
  })
_sym_db.RegisterMessage(VideoAnalyzerInput)

AnalyzerInferenceStatus = _reflection.GeneratedProtocolMessageType('AnalyzerInferenceStatus', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZERINFERENCESTATUS,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.AnalyzerInferenceStatus)
  })
_sym_db.RegisterMessage(AnalyzerInferenceStatus)

VideoAnalyzerOutput = _reflection.GeneratedProtocolMessageType('VideoAnalyzerOutput', (_message.Message,), {
  'DESCRIPTOR' : _VIDEOANALYZEROUTPUT,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.VideoAnalyzerOutput)
  })
_sym_db.RegisterMessage(VideoAnalyzerOutput)

AnalyzerOutputVideo = _reflection.GeneratedProtocolMessageType('AnalyzerOutputVideo', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEROUTPUTVIDEO,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.AnalyzerOutputVideo)
  })
_sym_db.RegisterMessage(AnalyzerOutputVideo)

AnalyzerOutputEvents = _reflection.GeneratedProtocolMessageType('AnalyzerOutputEvents', (_message.Message,), {
  'DESCRIPTOR' : _ANALYZEROUTPUTEVENTS,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.AnalyzerOutputEvents)
  })
_sym_db.RegisterMessage(AnalyzerOutputEvents)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
