# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ore.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from .github.com.envoyproxy.protoc_gen_validate.validate import validate_pb2 as github_dot_com_dot_envoyproxy_dot_protoc__gen__validate_dot_validate_dot_validate__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import meta_pb2 as meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ore.proto',
  package='apiserver.v2',
  syntax='proto3',
  serialized_options=b'Z-git.supremind.info/products/atom/proto/go/api',
  serialized_pb=b'\n\tore.proto\x12\x0c\x61piserver.v2\x1a\x41github.com/envoyproxy/protoc-gen-validate/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\nmeta.proto\"Z\n\x03Ore\x12.\n\x04meta\x18\x01 \x01(\x0b\x32\x16.apiserver.v2.MetadataB\x08\xfa\x42\x05\x8a\x01\x02\x08\x01\x12#\n\x04spec\x18\x02 \x01(\x0b\x32\x15.apiserver.v2.OreSpec\"\\\n\x07OreSpec\x12)\n\x08userData\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12&\n\x07rawInfo\x18\x02 \x01(\x0b\x32\x15.apiserver.v2.RawInfo\"n\n\x07RawInfo\x12/\n\x0crawItemInfos\x18\x01 \x03(\x0b\x32\x19.apiserver.v2.RawItemInfo\x12\x32\n\tvolumeRef\x18\x02 \x01(\x0b\x32\x1f.apiserver.v2.ResourceReference\",\n\x0bRawItemInfo\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x10\n\x08\x66ileSize\x18\x02 \x01(\x03\"\x7f\n\x0c\x43reateOreReq\x12\x37\n\x04name\x18\x01 \x01(\tB)\xfa\x42&r$\x18\xe8\x07\x32\x1f(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?\x12#\n\x04spec\x18\x02 \x01(\x0b\x32\x15.apiserver.v2.OreSpec\x12\x11\n\toverwrite\x18\x03 \x01(\x08\"D\n\tGetOreReq\x12\x37\n\x04name\x18\x01 \x01(\tB)\xfa\x42&r$\x18\xe8\x07\x32\x1f(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?\"l\n\x0cUpdateOreReq\x12\x37\n\x04name\x18\x01 \x01(\tB)\xfa\x42&r$\x18\xe8\x07\x32\x1f(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?\x12#\n\x04spec\x18\x02 \x01(\x0b\x32\x15.apiserver.v2.OreSpec\"G\n\x0cRemoveOreReq\x12\x37\n\x04name\x18\x01 \x01(\tB)\xfa\x42&r$\x18\xe8\x07\x32\x1f(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?2\xfb\x01\n\nOreService\x12:\n\tCreateOre\x12\x1a.apiserver.v2.CreateOreReq\x1a\x11.apiserver.v2.Ore\x12\x34\n\x06GetOre\x12\x17.apiserver.v2.GetOreReq\x1a\x11.apiserver.v2.Ore\x12:\n\tUpdateOre\x12\x1a.apiserver.v2.UpdateOreReq\x1a\x11.apiserver.v2.Ore\x12?\n\tRemoveOre\x12\x1a.apiserver.v2.RemoveOreReq\x1a\x16.google.protobuf.EmptyB/Z-git.supremind.info/products/atom/proto/go/apib\x06proto3'
  ,
  dependencies=[github_dot_com_dot_envoyproxy_dot_protoc__gen__validate_dot_validate_dot_validate__pb2.DESCRIPTOR,google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,meta__pb2.DESCRIPTOR,])




_ORE = _descriptor.Descriptor(
  name='Ore',
  full_name='apiserver.v2.Ore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='meta', full_name='apiserver.v2.Ore.meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\005\212\001\002\010\001', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec', full_name='apiserver.v2.Ore.spec', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=255,
)


_ORESPEC = _descriptor.Descriptor(
  name='OreSpec',
  full_name='apiserver.v2.OreSpec',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userData', full_name='apiserver.v2.OreSpec.userData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rawInfo', full_name='apiserver.v2.OreSpec.rawInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=349,
)


_RAWINFO = _descriptor.Descriptor(
  name='RawInfo',
  full_name='apiserver.v2.RawInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rawItemInfos', full_name='apiserver.v2.RawInfo.rawItemInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volumeRef', full_name='apiserver.v2.RawInfo.volumeRef', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=461,
)


_RAWITEMINFO = _descriptor.Descriptor(
  name='RawItemInfo',
  full_name='apiserver.v2.RawItemInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='apiserver.v2.RawItemInfo.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileSize', full_name='apiserver.v2.RawItemInfo.fileSize', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=507,
)


_CREATEOREREQ = _descriptor.Descriptor(
  name='CreateOreReq',
  full_name='apiserver.v2.CreateOreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apiserver.v2.CreateOreReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B&r$\030\350\0072\037(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec', full_name='apiserver.v2.CreateOreReq.spec', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overwrite', full_name='apiserver.v2.CreateOreReq.overwrite', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=509,
  serialized_end=636,
)


_GETOREREQ = _descriptor.Descriptor(
  name='GetOreReq',
  full_name='apiserver.v2.GetOreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apiserver.v2.GetOreReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B&r$\030\350\0072\037(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=638,
  serialized_end=706,
)


_UPDATEOREREQ = _descriptor.Descriptor(
  name='UpdateOreReq',
  full_name='apiserver.v2.UpdateOreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apiserver.v2.UpdateOreReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B&r$\030\350\0072\037(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spec', full_name='apiserver.v2.UpdateOreReq.spec', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=708,
  serialized_end=816,
)


_REMOVEOREREQ = _descriptor.Descriptor(
  name='RemoveOreReq',
  full_name='apiserver.v2.RemoveOreReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='apiserver.v2.RemoveOreReq.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B&r$\030\350\0072\037(^//.|^/|^[a-zA-Z]+)?:?/.+(/$)?', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=818,
  serialized_end=889,
)

_ORE.fields_by_name['meta'].message_type = meta__pb2._METADATA
_ORE.fields_by_name['spec'].message_type = _ORESPEC
_ORESPEC.fields_by_name['userData'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
_ORESPEC.fields_by_name['rawInfo'].message_type = _RAWINFO
_RAWINFO.fields_by_name['rawItemInfos'].message_type = _RAWITEMINFO
_RAWINFO.fields_by_name['volumeRef'].message_type = meta__pb2._RESOURCEREFERENCE
_CREATEOREREQ.fields_by_name['spec'].message_type = _ORESPEC
_UPDATEOREREQ.fields_by_name['spec'].message_type = _ORESPEC
DESCRIPTOR.message_types_by_name['Ore'] = _ORE
DESCRIPTOR.message_types_by_name['OreSpec'] = _ORESPEC
DESCRIPTOR.message_types_by_name['RawInfo'] = _RAWINFO
DESCRIPTOR.message_types_by_name['RawItemInfo'] = _RAWITEMINFO
DESCRIPTOR.message_types_by_name['CreateOreReq'] = _CREATEOREREQ
DESCRIPTOR.message_types_by_name['GetOreReq'] = _GETOREREQ
DESCRIPTOR.message_types_by_name['UpdateOreReq'] = _UPDATEOREREQ
DESCRIPTOR.message_types_by_name['RemoveOreReq'] = _REMOVEOREREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ore = _reflection.GeneratedProtocolMessageType('Ore', (_message.Message,), {
  'DESCRIPTOR' : _ORE,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.Ore)
  })
_sym_db.RegisterMessage(Ore)

OreSpec = _reflection.GeneratedProtocolMessageType('OreSpec', (_message.Message,), {
  'DESCRIPTOR' : _ORESPEC,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.OreSpec)
  })
_sym_db.RegisterMessage(OreSpec)

RawInfo = _reflection.GeneratedProtocolMessageType('RawInfo', (_message.Message,), {
  'DESCRIPTOR' : _RAWINFO,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.RawInfo)
  })
_sym_db.RegisterMessage(RawInfo)

RawItemInfo = _reflection.GeneratedProtocolMessageType('RawItemInfo', (_message.Message,), {
  'DESCRIPTOR' : _RAWITEMINFO,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.RawItemInfo)
  })
_sym_db.RegisterMessage(RawItemInfo)

CreateOreReq = _reflection.GeneratedProtocolMessageType('CreateOreReq', (_message.Message,), {
  'DESCRIPTOR' : _CREATEOREREQ,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.CreateOreReq)
  })
_sym_db.RegisterMessage(CreateOreReq)

GetOreReq = _reflection.GeneratedProtocolMessageType('GetOreReq', (_message.Message,), {
  'DESCRIPTOR' : _GETOREREQ,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.GetOreReq)
  })
_sym_db.RegisterMessage(GetOreReq)

UpdateOreReq = _reflection.GeneratedProtocolMessageType('UpdateOreReq', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEOREREQ,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.UpdateOreReq)
  })
_sym_db.RegisterMessage(UpdateOreReq)

RemoveOreReq = _reflection.GeneratedProtocolMessageType('RemoveOreReq', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEOREREQ,
  '__module__' : 'ore_pb2'
  # @@protoc_insertion_point(class_scope:apiserver.v2.RemoveOreReq)
  })
_sym_db.RegisterMessage(RemoveOreReq)


DESCRIPTOR._options = None
_ORE.fields_by_name['meta']._options = None
_CREATEOREREQ.fields_by_name['name']._options = None
_GETOREREQ.fields_by_name['name']._options = None
_UPDATEOREREQ.fields_by_name['name']._options = None
_REMOVEOREREQ.fields_by_name['name']._options = None

_ORESERVICE = _descriptor.ServiceDescriptor(
  name='OreService',
  full_name='apiserver.v2.OreService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=892,
  serialized_end=1143,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOre',
    full_name='apiserver.v2.OreService.CreateOre',
    index=0,
    containing_service=None,
    input_type=_CREATEOREREQ,
    output_type=_ORE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOre',
    full_name='apiserver.v2.OreService.GetOre',
    index=1,
    containing_service=None,
    input_type=_GETOREREQ,
    output_type=_ORE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateOre',
    full_name='apiserver.v2.OreService.UpdateOre',
    index=2,
    containing_service=None,
    input_type=_UPDATEOREREQ,
    output_type=_ORE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveOre',
    full_name='apiserver.v2.OreService.RemoveOre',
    index=3,
    containing_service=None,
    input_type=_REMOVEOREREQ,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORESERVICE)

DESCRIPTOR.services_by_name['OreService'] = _ORESERVICE

# @@protoc_insertion_point(module_scope)
