[tool.poetry]
name = "subtitle-sync"
version = "0.2.7"
description = ""
authors = ["VVNoodle <brickkace@gmail.com>"]
exclude = ["mvp_screenplays/", "mvp_subtitles/", "matchingTest.json"]

[tool.poetry.dependencies]
python = "^3.7"
Scrapy = "^2.0.1"
subliminal = "^2.0.5"
srt = "^3.0.0"
spacy = "^2.2.4"
pysbd = "^0.2.3"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
