[tool.poetry]
name = "mongodb-dataset"
version = "0.1.3"
description = ""
authors = ["InnovativeInventor <root@max.fan>"]

[tool.poetry.dependencies]
python = "^3.8"
pymongo = "^3.10.1"
dnspython = "^1.16.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
