[tool.poetry]
name = "neo4j-gds"
version = "0.1.1"
description = "Library to build neo4j's queries with special attention on Graph Data Science library calls"
authors = ["Pablo Cabezas <pabcabsal@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
py2neo = "^5.0b5"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
12factor-configclasses = "^0.3.0"
python-dotenv = "^0.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
