
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-14T17:09:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6aa6b293d328ec5b94790907dbb8775fffeefa34",
 "version": "0.9.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
