[tool.poetry]
name = "ankidmpy"
version = "0.1.0"
description = "Python port of github.com/OnkelTem/anki-dm"
authors = ["Douglas Mennella <trx2358-pypi@yahoo.com>"]
license = "MIT"
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
anki-dm ="ankidmpy:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

