#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='yaxi',
      version='0.1.0',
      description='Yet Another Xml Interface; terse queries using slices and calls with no deps.',
      author='Stefan Countryman',
      author_email='stefan.countryman@gmail.com',
      url='https://github.com/stefco/yaxi',
      py_modules=['yaxi'],
     )
