create database	testorm;                                                                          
grant all privileges on database testorm to collector;                                           
\c testorm;                                                                                       
CREATE EXTENSION postgis;                                                                         
CREATE EXTENSION postgis_topology;                                                                
CREATE EXTENSION fuzzystrmatch;                                                                   
CREATE EXTENSION address_standardizer;                                                            
CREATE EXTENSION address_standardizer_data_us;                                                    
CREATE EXTENSION postgis_tiger_geocoder;                                                          
CREATE EXTENSION postgis_sfcgal;       
