[tool.poetry]
name = "shrtcodes"
version = "0.3.0"
description = "Simple shortcodes for Python."
authors = ["Peter Byfield <byfield554@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Peter554/shrtcodes#readme"
repository = "https://github.com/Peter554/shrtcodes"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
mypy = "^0.782"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
