factory: form
name: ldap_roles_settings
props:
    action: context.form_action
    class: ajax
widgets:
- roles_dn:
    factory: field:label:help:error:text
    value: expr:context.model.attrs.roles_dn
    props:
        label: i18n:roles_dn:Roles container DN
        help: i18n:roles_dn_help:LDAP DN of container with roles
        required: i18n:roles_dn_required:No Roles DN defined
- roles_scope:
    factory: field:label:help:select
    value: expr:context.model.attrs.roles_scope
    props:
        label: i18n:roles_scope:Roles search scope
        help: i18n:roles_scope_help:LDAP search scope for roles
        vocabulary: expr:context.scope_vocab
- roles_query:
    factory: field:label:help:text
    value: expr:context.model.attrs.roles_query
    props:
        label: i18n:roles_query:Roles search query filter
        help: i18n:roles_query_help:Custom LDAP query for role objects
- roles_object_classes:
    factory: field:label:help:text
    value: expr:u', '.join(context.model.attrs.get('roles_object_classes', []))
    props:
        label: i18n:roles_object_classes:Object classes for role creation
        help: i18n:roles_object_classes_help:LDAP object class names
- roles_aliases_attrmap:
    factory: field:label:help:error:dict
    value: expr:context.roles_aliases_attrmap
    props:
        label: i18n:roles_aliases_attrmap:Role attribute aliases
        help: i18n:roles_aliases_attrmap_help:Aliases for reserved attribute keys
        required: i18n:roles_aliases_attrmap_required:Role attribute aliases values are mandatory
        static: True
        key_label: i18n:reserved_key:Reserved key
        value_label: i18n:ldap_attr_name:LDAP attribute name
#- roles_relation:
#    factory: field:label:text
#    value: expr:context.model.attrs.roles_relation
#    props:
#        label: Role-member-relation
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save:Save