factory: form
name: ldap_server_settings
props:
    action: context.form_action
    class: ajax
widgets:
- uri:
    factory: field:label:error:text
    value: expr:context.model.attrs.uri
    props:
        label: i18n:ldap_uri:LDAP URI
        required: i18n:ldap_uri_required:No URI defined
- user:
    factory: field:label:error:text
    value: expr:context.model.attrs.user
    props:
        label: i18n:ldap_manager_user:LDAP manager user
        required: i18n:ldap_manager_user_required:No user defined
- password:
    factory: field:label:error:password
    value: expr:context.model.attrs.password
    props:
        label: i18n:ldap_manager_password:LDAP manager password
        required: i18n:ldap_manager_password_required:No password defined
- cache:
    factory: field:label:checkbox
    value: expr:int(context.model.attrs.cache)
    props:
        label: i18n:ldap_cache_query_results:Enable caching for LDAP query results
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save:Save