# Generated by Django 2.1.7 on 2020-07-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200702_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='erro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='uf',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='versao',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='versaoitem',
            options={'managed': False},
        ),
    ]
