---
- name: setup workoutizer
  hosts: localhost
  connection: local
  vars:
    - ansible_python_interpreter: "{{ '/usr/bin/python3' }}"

  tasks:

  - name: install required apt packages
    become: yes
    apt:
      name: "{{ packages }}"
      update_cache: yes
    vars:
      packages:
        - gvfs
        - gvfs-fuse
        - gvfs-bin
        - gvfs-backends
        - ifuse
    register: installed

  - name: copy udev rule for automated mounting
    become: yes
    template:
      src: files/device_mount.rules
      dest: /etc/udev/rules.d/device_mount.rules

  - name: copy workoutizer systemd service file to pi
    become: yes
    copy:
      src: files/wkz_mount.service
      dest: /etc/systemd/system/wkz_mount.service

  - name: enable wkz_mount systemd service
    become: yes
    systemd:
      enabled: yes
      name: wkz_mount.service
      state: stopped
...