# Generated by Django 3.0.6 on 2020-06-24 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_auto_20200623_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timesheetitem',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='timesheetstatistic',
            name='category',
        ),
        migrations.RemoveField(
            model_name='timesheetstatistic',
            name='sheet',
        ),
        migrations.DeleteModel(
            name='TimeSheet',
        ),
        migrations.DeleteModel(
            name='TimeSheetItem',
        ),
        migrations.DeleteModel(
            name='TimeSheetStatistic',
        ),
    ]
