#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['desugar']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['black==19.10b0'], 'test': ['pytest==5.4.3']}

setup(name='desugar',
      version='0',
      description='Re-implement the parts of Python that allow removing its syntactic sugar.',
      author='Brett Cannon',
      author_email='brett@python.org',
      url='https://github.com/brettcannon/desugar',
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
