[tool.poetry]
name = "matt"
version = "0.1.0"
description = "A maths test"
authors = ["Noisytoot <noisytoot@gmail.com>"]
license = "GPL-3.0-or-later"
repository = "https://git.noisytoot.org/noisytoot/matt"

[tool.poetry.dependencies]
python = "^3.8"
termcolor = "^1.1.0"
colorama = { version = "^0.4.3", platform = "windows" }
pyxdg = "^0.26"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
