
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-11T21:11:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "29c1c0b96956c0500a11a67e482f8a7443e66f70",
 "version": "1.3.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
