name: thelper
channels:
  - pytorch
  - conda-forge
dependencies:
  - cython
  - ddt
  - gitdb
  - gitpython
  - lz4
  - matplotlib
  - numpy
  - opencv
  # PILLOW_VERSION removed which causes torchvision<=0.4.0 to fail
  - pillow<7
  - pip
  - pytorch<1.3
  - pyyaml
  - scikit-learn
  - six
  - torchvision
  - tqdm
  - pip:
    - h5py
    - opencv-python
    - tensorboardX
