XKCD_COLS = {"purple", "green", "blue", "pink", "brown", "red", "light blue",
             "teal", "orange", "light green", "magenta", "yellow", "sky blue",
             "grey", "lime green", "light purple", "violet", "dark green",
             "turquoise", "lavender", "dark blue", "tan", "cyan", "aqua",
             "forest green", "mauve", "dark purple", "bright green", "maroon",
             "olive", "salmon", "beige", "royal blue", "navy blue", "lilac",
             "black", "hot pink", "light brown", "pale green", "peach",
             "olive green", "dark pink", "periwinkle", "sea green", "lime",
             "indigo", "mustard", "light pink", "rose", "bright blue",
             "neon green", "burnt orange", "aquamarine", "navy", "grass green",
             "pale blue", "dark red", "bright purple", "yellow green",
             "baby blue", "gold", "mint green", "plum", "royal purple",
             "brick red", "dark teal", "burgundy", "khaki", "blue green",
             "seafoam green", "kelly green", "puke green", "pea green",
             "taupe", "dark brown", "deep purple", "chartreuse", "bright pink",
             "light orange", "mint", "pastel green", "sand", "dark orange",
             "spring green", "puce", "seafoam", "grey blue", "army green",
             "dark grey", "dark yellow", "goldenrod", "slate", "light teal",
             "rust", "deep blue", "pale pink", "cerulean", "light red",
             "mustard yellow", "ochre", "pale yellow", "crimson", "fuchsia",
             "hunter green", "blue grey", "slate blue", "pale purple",
             "sea blue", "pinkish purple", "puke", "light grey", "leaf green",
             "light yellow", "eggplant", "steel blue", "moss green",
             "robin's egg blue", "white", "grey green", "sage", "brick",
             "burnt sienna", "reddish brown", "cream", "coral", "ocean blue",
             "greenish", "dark magenta", "red orange", "bluish purple",
             "midnight blue", "light violet", "dusty rose", "medium blue",
             "greenish yellow", "yellowish green", "purplish blue",
             "greyish blue", "grape", "light olive", "cornflower blue",
             "pinkish red", "bright red", "azure", "blue purple",
             "dark turquoise", "electric blue", "off white", "powder blue",
             "wine", "dull green", "apple green", "light turquoise",
             "neon purple", "cobalt", "pinkish", "olive drab", "dark cyan",
             "purple blue", "dark violet", "dark lavender", "forrest green",
             "vomit", "pale orange", "greenish blue", "dark tan", "green blue",
             "bluish green", "pastel blue", "moss", "grass", "deep pink",
             "blood red", "sage green", "aqua blue", "terracotta",
             "pastel purple", "sienna", "dark olive", "green yellow",
             "scarlet", "greyish green", "chocolate", "blue violet",
             "cornflower", "baby pink", "charcoal", "pine green", "pumpkin",
             "greenish brown", "red brown", "brownish green", "tangerine",
             "salmon pink", "aqua green", "raspberry", "greyish purple",
             "rose pink", "neon pink", "cobalt blue", "orange brown",
             "deep red", "orange red", "dirty yellow", "orchid",
             "reddish pink", "reddish purple", "yellow orange", "light cyan",
             "sky", "light magenta", "pale red", "emerald", "dark beige",
             "ugly green", "jade", "greenish grey", "dark salmon",
             "purplish pink", "dark aqua", "brownish orange", "olive green",
             "light aqua", "clay", "medium green", "burnt umber", "dull blue",
             "pale brown", "emerald green", "brownish", "mud", "dark rose",
             "brownish red", "pink purple", "pinky purple", "camo green",
             "faded green", "dusty pink", "purple pink", "vomit green",
             "deep green", "reddish orange", "mahogany", "aubergine",
             "dull pink", "evergreen", "sky blue", "light green",
             "pastel pink", "grey purple", "light blue", "dark mauve",
             "cadet blue", "ice blue", "light tan", "dirty green", "neon blue",
             "wine red", "chocolate brown", "dull purple", "yellow brown",
             "denim", "eggshell", "jungle green", "dark peach", "poop",
             "umber", "light lavender", "bright yellow", "golden yellow",
             "dusty blue", "electric green", "lighter green", "slate grey",
             "teal green", "marine blue", "avocado", "terra cotta",
             "dusty purple", "light maroon", "reddish", "dark lilac",
             "dark periwinkle", "bluish grey", "puke yellow", "purplish",
             "ultramarine", "barney purple", "forest", "pea soup",
             "brownish yellow", "bright teal", "bluegreen", "green brown",
             "blurple", "sky blue", "periwinkle blue", "pale violet",
             "darker green", "true blue", "green grey", "grey brown",
             "olive green", "apricot", "faded purple", "darker blue", "cerise",
             "khaki green", "burnt red", "forest green", "violet blue",
             "pale lavender", "acid green", "purple grey", "lemon",
             "bright orange", "soft green", "blush", "yellowish brown",
             "fluorescent green", "electric purple", "steel", "dull orange",
             "muddy green", "marigold", "ocean", "light mauve", "bordeaux",
             "blue green", "yellowish", "snot green", "lime green",
             "drab green", "faded blue", "forest green", "hot purple",
             "dark maroon", "brown green", "swamp green", "light indigo",
             "purpley blue", "lightish blue", "teal blue", "denim blue",
             "lime green", "dull yellow", "pistachio", "lemon yellow",
             "red violet", "dusky pink", "dirt", "dark green", "medium purple",
             "shit", "dark mustard", "soup green", "bubblegum pink",
             "barbie pink", "military green", "pale teal", "bronze",
             "pinky red", "dull red", "darkish blue", "bluish", "dark gold",
             "yellowy green", "pine", "blue green", "dirty pink",
             "slate green", "prussian blue", "bright violet", "lighter purple",
             "steel grey", "russet", "vermillion", "greyish brown",
             "red purple", "red pink", "bright turquoise", "golden brown",
             "cerulean blue", "soft blue", "easter green", "amber", "mid blue",
             "shit brown", "hospital green", "purpleish blue", "purply blue",
             "silver", "sickly green", "melon", "dusky rose", "brown orange",
             "darkish green", "cranberry", "purpleish", "ecru",
             "darker purple", "mocha", "bright magenta", "coffee", "sepia",
             "faded red", "canary yellow", "bluey purple", "pastel yellow",
             "pale turquoise", "greyish pink", "marine", "purplish grey",
             "camel", "brownish grey", "burnt yellow", "cherry red",
             "orangey brown", "soft pink", "sea green", "aqua marine",
             "egg blue", "sea green", "mud brown", "sandstone", "racing green",
             "faded pink", "maize", "ocre", "orange yellow", "dark khaki",
             "light lime", "light blue", "jade green", "barney", "adobe",
             "minty green", "navy blue", "dusty green", "dark blue",
             "ocean green", "mustard green", "poop brown", "olive brown",
             "pink red", "light navy", "light purple", "ivory",
             "bright lavender", "bright aqua", "robin's egg", "muted green",
             "medium brown", "copper", "dark lime", "strawberry", "dirt brown",
             "celery", "sky blue", "poo brown", "pinkish brown", "celadon",
             "lime green", "auburn", "shocking pink", "mulberry",
             "carolina blue", "lightish green", "light lilac", "pale olive",
             "pumpkin orange", "yellow ochre", "engine red", "sky blue",
             "watermelon", "bottle green", "dark purple", "wheat",
             "murky green", "brownish purple", "kermit green", "primary blue",
             "orangey red", "pale lilac", "rust red", "dirty orange",
             "pinkish grey", "light plum", "greeny blue", "dark navy",
             "pink/purple", "irish green", "baby poop", "slime green",
             "purplish red", "rouge", "light rose", "drab", "navy blue",
             "yellow green", "easter purple", "snot", "light salmon",
             "purpley pink", "poo", "berry", "medium grey", "brown red",
             "blood", "soft purple", "grey pink", "bluey green", "midnight",
             "dark indigo", "warm grey", "sandy brown", "cherry",
             "blue/purple", "gunmetal", "deep violet", "tree green",
             "orangish brown", "shamrock green", "orangish red",
             "greeny yellow", "ugly yellow", "french blue", "dusky purple",
             "butter yellow", "light beige", "golden", "dusky blue",
             "lightblue", "purply pink", "off green", "ocher",
             "milk chocolate", "light peach", "deep magenta", "caramel",
             "greenish teal", "pale lime", "purple red", "blueberry",
             "asparagus", "pale grey", "grey blue", "lime green",
             "grassy green", "mossy green", "earth", "deep orange",
             "pale aqua", "rose red", "stone", "rusty orange", "pea",
             "sick green", "darker pink", "chestnut", "blue/green", "amethyst",
             "mint green", "pale rose", "muted blue", "fawn", "buff",
             "turquoise green", "muddy brown", "sea", "tomato",
             "carnation pink", "banana", "neon yellow", "greyish", "mid green",
             "muted purple", "electric pink", "sandy", "ugly pink",
             "turquoise blue", "light burgundy", "greenish tan", "dark mint",
             "light urple", "midnight purple", "pinkish orange", "pear",
             "dark plum", "tealish", "perrywinkle", "yellowish orange",
             "pastel orange", "iris", "ultramarine blue", "navy green",
             "seaweed", "kiwi", "fluro green", "light green", "vivid green",
             "frog green", "dull brown", "dusk", "mustard brown",
             "leafy green", "cool blue", "almost black", "yellow/green",
             "heliotrope", "green apple", "poop green", "apple",
             "purpleish pink", "night blue", "merlot", "lightgreen",
             "tomato red", "key lime", "pale cyan", "vomit yellow",
             "purplish brown", "bubblegum", "shamrock", "mango", "lime yellow",
             "hot green", "grape purple", "faded orange", "avocado green",
             "peacock blue", "weird green", "bright lilac", "fern green",
             "dirty blue", "rust orange", "heather", "deep teal",
             "dark seafoam", "baby poo", "yellowgreen", "light sage",
             "light aquamarine", "spearmint", "bright lime", "vibrant green",
             "pale green", "faded yellow", "bile", "viridian", "light pink",
             "puke brown", "medium pink", "ugly purple", "sunshine yellow",
             "seaweed green", "light periwinkle", "lemon green",
             "greeny brown", "grey blue", "bright olive", "turtle green",
             "sky blue", "light mustard", "diarrhea", "dark aquamarine",
             "brownish pink", "shit green", "purpley", "greyblue",
             "hot magenta", "blue/grey", "pale", "cool green", "sandy yellow",
             "eggshell blue", "barf green", "baby green", "vibrant purple",
             "brown grey", "water blue", "lipstick red", "banana yellow",
             "wisteria", "purple brown", "brown yellow", "purple/pink",
             "lemon lime", "grey/blue", "dusty red", "deep rose",
             "seafoam green", "muddy yellow", "carnation", "yellowy brown",
             "violet red", "twilight blue", "pure blue", "lightish red",
             "brick orange", "velvet", "sunflower", "mint green",
             "grass green", "lavender blue", "rusty red", "lightish purple",
             "dried blood", "blue grey", "leaf", "orangish", "olive green",
             "off yellow", "dusty orange", "butter", "royal", "petrol",
             "greenish cyan", "egg blue", "gum pink", "bluegrey", "warm brown",
             "twilight", "saffron", "purple/blue", "dark sand", "vibrant blue",
             "putty", "lawn green", "camouflage green", "blush pink",
             "reddy brown", "darkish red", "algae green", "dark coral",
             "bright cyan", "piss yellow", "pastel red", "greenish turquoise",
             "dark", "ruby", "poop green", "orangered", "dandelion", "claret",
             "pale mauve", "lipstick", "rosa", "darkblue", "tan brown",
             "shit green", "red wine", "pinky", "mud green", "greenish blue",
             "dull teal", "deep lavender", "vivid blue", "raw umber",
             "light mint", "light blue", "highlighter green", "greeny grey",
             "bluey grey", "algae", "sap green", "pale salmon",
             "metallic blue", "ice", "gross green", "dodger blue", "warm pink",
             "green blue", "flat green", "blue grey", "clay brown",
             "sand yellow", "grapefruit", "blood orange", "pale blue",
             "old pink", "neon red", "golden rod", "plum purple", "pale peach",
             "green again", "yellow green", "carmine", "sea blue", "hot pink",
             "warm blue", "light khaki", "icky green", "greenblue",
             "dirty purple", "rich blue", "mushroom", "flat blue",
             "slate blue", "dark sage", "coral pink", "true green",
             "darkish purple", "dark taupe", "cool grey", "canary",
             "booger green", "muted pink", "hazel", "royal blue",
             "vivid purple", "racing green", "leather", "green/blue",
             "sunflower yellow", "rich purple", "pale magenta",
             "yellowish green", "indigo blue", "dark fuchsia", "yellow tan",
             "wintergreen", "violet pink", "topaz", "seafoam blue",
             "light gold", "grey/green", "foam green", "creme", "clear blue",
             "ugly blue", "terracota", "dark brown", "straw", "parchment",
             "orangey yellow", "greyish teal", "sapphire", "nice blue",
             "browny orange", "out green", "tiffany blue", "light seafoam",
             "neon green", "bright green", "bluish green", "rosy pink",
             "peachy pink", "light green", "old rose", "fern", "dusk blue",
             "camo", "burnt siena", "tealish green", "swamp", "sand brown",
             "rust brown", "orangeish", "royal blue", "cocoa", "baby purple",
             "raw sienna", "radioactive green", "pea green", "cinnamon",
             "squash", "charcoal grey", "yellow green", "puke green",
             "poison green", "light lavendar", "indian red", "dark cream",
             "toupe", "butterscotch", "burple", "tan green", "sun yellow",
             "pale gold", "light green", "lichen", "green/yellow", "darkgreen",
             "azul", "sunny yellow", "sickly yellow", "kelley green", "bruise",
             "browny green", "battleship grey", "off blue", "manilla",
             "greenish beige", "deep brown", "darkish pink", "custard",
             "ugly brown", "stormy blue", "liliac", "shit brown",
             "reddish grey", "powder pink", "eggplant purple", "egg shell",
             "light brown", "tea green", "orange pink", "grey green",
             "kiwi green", "boring green", "pastel green", "candy pink",
             "purply", "purpley grey", "dusty lavender", "desert",
             "deep lilac", "pig pink", "olive yellow", "seafoam green",
             "moss green", "lavender pink", "deep aqua", "bland",
             "strong pink", "green teal", "deep turquoise", "green blue",
             "sea green", "booger", "of purple", "blue blue", "windows blue",
             "toxic green", "strong blue", "spruce", "pinkish tan",
             "and cheese", "grey teal", "dusty teal", "grass green", "cement",
             "yellowish tan", "warm purple", "tea", "light blue",
             "nasty green", "light eggplant", "fresh green", "electric lime",
             "dust", "pastel green", "cloudy blue"}
