sudo: false
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev # provides unbuffer utility

language: python

stages:
  - linting
  - test

python:
  - "3.6"

jobs:
  include:
    - stage: linting
      name: "Pre-Commit"
      python: 3.6
      install: pip install pre_commit
      script: pre-commit run --all

install:
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - export PATH=.travis:${PATH}

script:
  - travis_run_tests
