[tool.poetry]
name = "yatb"
version = "0.0.3"
description = "Yet Another Telegram Bot implementation"
authors = ["denolehov <denolehov@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.1"
pydantic = "^1.5.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.8.3"
isort = {extras = ["pyproject"], version = "^4.3.21"}
pre-commit = "^2.5.1"
mypy = "^0.782"
ipython = "^7.16.1"
pytest = "^5.4.3"
pytest-asyncio = "^0.14.0"
faker = "^4.1.1"
httpx = "^0.13.3"
aiohttp = "^3.6.2"
requests = "^2.24.0"
pytest-httpserver = "^0.3.4"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
line_length = 88
multi_line_output = 3
include_trailing_comma = 'True'
force_grid_wrap = 0
combine_as_imports = 'True'

[tool.poetry.scripts]
yatb = "yatb.console:yatb"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
