[tool.poetry]
name = "ankidmpy"
version = "0.1.1"
description = "Python port of github.com/OnkelTem/anki-dm"
authors = ["Douglas Mennella <trx2358-pypi@yahoo.com>"]
license = "MIT"
readme = 'README.md'
homepage = ""
repository = "https://github.com/gitonthescene/ankidmpy"
keywords = ["Anki",
            "CrowdAnki",
            "flash cards"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
anki-dm ="ankidmpy:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tools.poetry.urls]
issues = "https://github.com/gitonthescene/ankidmpy/issues"