
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-12T14:16:11-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "27d62f3b42950254bb5839d81f2e83d51a605a9c",
 "version": "20.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
