language: python
cache: pip
dist: xenial
python: 3.7

matrix:
  include:
    - name: Check black formatting
      env: TOXENV=black
    - name: Check flake8 on Python 3
      env: TOXENV=flake8
    - name: Check license headers
      env: TOXENV=license

install:
  - pip install tox

script:
  - tox
