language: python

addons:
  apt:
    packages:
    - swig
    - libssl-dev
    - libssl1.0.0
    - python-setuptools
    - python-twisted

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"

install:
  - travis_retry pip install Twisted
  - python setup.py install

script: python setup.py test
