main:

  - name: fps
    label: Frames Per Second
    type: int
    range: 1,200
    default: 30
  - name: scale
    label: Output Scale
    type: double
    default: 1.0
    range: 0.1,1.0
  - name: open_when_done
    label: Open When Done Saving
    type: bool
    default: false
