[tool.poetry]
name = "demoben"
version = "0.1.2"
description = ""
authors = ["Ben-Cheng <bcheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
pytest-3 = "^3.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
