# Generated by Django 2.1.7 on 2020-07-02 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0003_auto_20200702_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grupologin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grupouser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pontofuncao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pontofuncaorelacao',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': True},
        ),
    ]
