
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-03T23:14:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a5b867a547fe9f63631470b4c89596e7f5a577cb",
 "version": "v0.5.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
