[tool.poetry]
name = "quickest"
version = "0.1.0"
description = "Tools for studying change detection problems. The justification for this package is that there are libraries for studying Markov chains, and there are libraries for numeric optimisation, but there is no standalone library for optimising the parameters of a Markov decision process."
authors = ["Jenna Riseley <j2.riseley@qut.edu.au>"]

[tool.poetry.dependencies]
python = "^3.7"
pyyaml = "^5.3.1"
scipy = "^1.4.1"
numpy = "^1.16.4"
matplotlib = "^3.2.1"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
pylint = "^2.5.3"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
