
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-10T13:11:32+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2365d96d08d5dbb128e7b037f51cd78943e39d2",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
