---
- name: Install debian required packages
  apt:
    name:
      - git
      - sudo
      - vim
    state: present
- name: get the rpm or apt package facts
  package_facts:
    manager: "auto"
- name: Install DEB teleport
  become: yes
  apt:
    deb: https://get.gravitational.com/teleport_4.2.9_amd64.deb
  when: "'teleport' not in ansible_facts.packages"
- name: Set locale
  shell: localedef -c -i fr_FR -f UTF-8 fr_FR.UTF-8 && echo "LANG=fr_FR.UTF-8" > /etc/locale.conf
