[tool.poetry]
# https://poetry.eustace.io/docs/pyproject/
name = "docci"
version = "1.1.0"
description = "Various document utils"
authors = ["potykion <potykion@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/potykion/docci"

[tool.poetry.dependencies]
python = "^3.7"
openpyxl = "^3.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pre-commit = "^1.15"
mypy = "^0.701.0"
flake8 = "^3.7"
black = {version = "^18.3-alpha.0",allow-prereleases = true}
pydocstyle = "^3.0"
bump2version = "^0.5.11"
sphinx = "^2.3"

[tool.black]
# https://black.readthedocs.io/en/stable/installation_and_usage.html#command-line-options
line-length = 98
skip-string-normalization = true
target-version = ['py37']

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

