language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - name: Check black formatting
      python: 3.6
      env: TOXENV=black
    - name: Check flake8 on Python 2
      python: 2.7
      env: TOXENV=flake8
    - name: Check flake8 on Python 3
      python: 3.6
      env: TOXENV=flake8
    - name: Check license headers
      python: 3.7
      env: TOXENV=license

install:
  - pip install tox

script:
  - tox
