# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiYarnApplicationDiagnosticsCollectionArgs(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'application_ids': 'list[str]',
        'ticket_number': 'str',
        'comments': 'str'
    }

    attribute_map = {
        'application_ids': 'applicationIds',
        'ticket_number': 'ticketNumber',
        'comments': 'comments'
    }

    def __init__(self, application_ids=None, ticket_number=None, comments=None):
        """
        ApiYarnApplicationDiagnosticsCollectionArgs - a model defined in Swagger
        """

        self._application_ids = None
        self._ticket_number = None
        self._comments = None

        if application_ids is not None:
          self.application_ids = application_ids
        if ticket_number is not None:
          self.ticket_number = ticket_number
        if comments is not None:
          self.comments = comments

    @property
    def application_ids(self):
        """
        Gets the application_ids of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Id's of the applications whose diagnostics data has to be collected

        :return: The application_ids of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :rtype: list[str]
        """
        return self._application_ids

    @application_ids.setter
    def application_ids(self, application_ids):
        """
        Sets the application_ids of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Id's of the applications whose diagnostics data has to be collected

        :param application_ids: The application_ids of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :type: list[str]
        """

        self._application_ids = application_ids

    @property
    def ticket_number(self):
        """
        Gets the ticket_number of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Ticket Number of the Cloudera Support Ticket

        :return: The ticket_number of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :rtype: str
        """
        return self._ticket_number

    @ticket_number.setter
    def ticket_number(self, ticket_number):
        """
        Sets the ticket_number of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Ticket Number of the Cloudera Support Ticket

        :param ticket_number: The ticket_number of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :type: str
        """

        self._ticket_number = ticket_number

    @property
    def comments(self):
        """
        Gets the comments of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Comments to add to the support bundle

        :return: The comments of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """
        Sets the comments of this ApiYarnApplicationDiagnosticsCollectionArgs.
        Comments to add to the support bundle

        :param comments: The comments of this ApiYarnApplicationDiagnosticsCollectionArgs.
        :type: str
        """

        self._comments = comments

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiYarnApplicationDiagnosticsCollectionArgs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
