# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiHostsPerfInspectorArgs(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_host_list': 'ApiHostNameList',
        'target_host_list': 'ApiHostNameList',
        'ping_args': 'ApiPerfInspectorPingArgs'
    }

    attribute_map = {
        'source_host_list': 'sourceHostList',
        'target_host_list': 'targetHostList',
        'ping_args': 'pingArgs'
    }

    def __init__(self, source_host_list=None, target_host_list=None, ping_args=None):
        """
        ApiHostsPerfInspectorArgs - a model defined in Swagger
        """

        self._source_host_list = None
        self._target_host_list = None
        self._ping_args = None

        if source_host_list is not None:
          self.source_host_list = source_host_list
        if target_host_list is not None:
          self.target_host_list = target_host_list
        if ping_args is not None:
          self.ping_args = ping_args

    @property
    def source_host_list(self):
        """
        Gets the source_host_list of this ApiHostsPerfInspectorArgs.
        Required list of host names which'll act as source for running network diagnostics test.

        :return: The source_host_list of this ApiHostsPerfInspectorArgs.
        :rtype: ApiHostNameList
        """
        return self._source_host_list

    @source_host_list.setter
    def source_host_list(self, source_host_list):
        """
        Sets the source_host_list of this ApiHostsPerfInspectorArgs.
        Required list of host names which'll act as source for running network diagnostics test.

        :param source_host_list: The source_host_list of this ApiHostsPerfInspectorArgs.
        :type: ApiHostNameList
        """

        self._source_host_list = source_host_list

    @property
    def target_host_list(self):
        """
        Gets the target_host_list of this ApiHostsPerfInspectorArgs.
        Required list of host names which'll act as target for running network diagnostics test.

        :return: The target_host_list of this ApiHostsPerfInspectorArgs.
        :rtype: ApiHostNameList
        """
        return self._target_host_list

    @target_host_list.setter
    def target_host_list(self, target_host_list):
        """
        Sets the target_host_list of this ApiHostsPerfInspectorArgs.
        Required list of host names which'll act as target for running network diagnostics test.

        :param target_host_list: The target_host_list of this ApiHostsPerfInspectorArgs.
        :type: ApiHostNameList
        """

        self._target_host_list = target_host_list

    @property
    def ping_args(self):
        """
        Gets the ping_args of this ApiHostsPerfInspectorArgs.
        Optional ping request arguments. If not specified, default arguments will be used for ping test.

        :return: The ping_args of this ApiHostsPerfInspectorArgs.
        :rtype: ApiPerfInspectorPingArgs
        """
        return self._ping_args

    @ping_args.setter
    def ping_args(self, ping_args):
        """
        Sets the ping_args of this ApiHostsPerfInspectorArgs.
        Optional ping request arguments. If not specified, default arguments will be used for ping test.

        :param ping_args: The ping_args of this ApiHostsPerfInspectorArgs.
        :type: ApiPerfInspectorPingArgs
        """

        self._ping_args = ping_args

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiHostsPerfInspectorArgs):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
