# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiServiceConfig(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[ApiConfig]',
        'role_type_configs': 'list[ApiRoleTypeConfig]'
    }

    attribute_map = {
        'items': 'items',
        'role_type_configs': 'roleTypeConfigs'
    }

    def __init__(self, items=None, role_type_configs=None):
        """
        ApiServiceConfig - a model defined in Swagger
        """

        self._items = None
        self._role_type_configs = None

        if items is not None:
          self.items = items
        if role_type_configs is not None:
          self.role_type_configs = role_type_configs

    @property
    def items(self):
        """
        Gets the items of this ApiServiceConfig.
        

        :return: The items of this ApiServiceConfig.
        :rtype: list[ApiConfig]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this ApiServiceConfig.
        

        :param items: The items of this ApiServiceConfig.
        :type: list[ApiConfig]
        """

        self._items = items

    @property
    def role_type_configs(self):
        """
        Gets the role_type_configs of this ApiServiceConfig.
        List of role type configurations. Only available up to API v2.

        :return: The role_type_configs of this ApiServiceConfig.
        :rtype: list[ApiRoleTypeConfig]
        """
        return self._role_type_configs

    @role_type_configs.setter
    def role_type_configs(self, role_type_configs):
        """
        Sets the role_type_configs of this ApiServiceConfig.
        List of role type configurations. Only available up to API v2.

        :param role_type_configs: The role_type_configs of this ApiServiceConfig.
        :type: list[ApiRoleTypeConfig]
        """

        self._role_type_configs = role_type_configs

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiServiceConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
