# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ApiTimeSeries(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'metadata': 'ApiTimeSeriesMetadata',
        'data': 'list[ApiTimeSeriesData]'
    }

    attribute_map = {
        'metadata': 'metadata',
        'data': 'data'
    }

    def __init__(self, metadata=None, data=None):
        """
        ApiTimeSeries - a model defined in Swagger
        """

        self._metadata = None
        self._data = None

        if metadata is not None:
          self.metadata = metadata
        if data is not None:
          self.data = data

    @property
    def metadata(self):
        """
        Gets the metadata of this ApiTimeSeries.
        Metadata for the metric.

        :return: The metadata of this ApiTimeSeries.
        :rtype: ApiTimeSeriesMetadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata):
        """
        Sets the metadata of this ApiTimeSeries.
        Metadata for the metric.

        :param metadata: The metadata of this ApiTimeSeries.
        :type: ApiTimeSeriesMetadata
        """

        self._metadata = metadata

    @property
    def data(self):
        """
        Gets the data of this ApiTimeSeries.
        List of metric data points.

        :return: The data of this ApiTimeSeries.
        :rtype: list[ApiTimeSeriesData]
        """
        return self._data

    @data.setter
    def data(self, data):
        """
        Sets the data of this ApiTimeSeries.
        List of metric data points.

        :param data: The data of this ApiTimeSeries.
        :type: list[ApiTimeSeriesData]
        """

        self._data = data

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ApiTimeSeries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
