[tool.poetry]
name = "shell-util"
version = "0.1.8"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
repository = 'https://github.com/eyalev/shell-util'
readme = "README.md"

[tool.poetry.scripts]
shell = "shell_util.cli:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
dataclasses = { version = "^0.7", python = "~3.6" }


[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^19.10b0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
