
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-11T14:11:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e99646f06f9501994e42ff490f04cb086640b211",
 "version": "1.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
