[tool.poetry]
name = "benpkg"
version = "0.3.0"
description = ""
authors = ["Ben-Cheng <bcheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
