trait = "is-sensor"
doc = """
Daemons with the is-sensor trait are capable of measuring some unknown quantities.
Sensor daemons may have multiple channels if a single measurement returns multiple values.
"""
requires = []

[messages]

[messages.measure]
doc = "Initiate a measurement. Returns integer, measurement ID."
request = [
  {"name"="loop", "type"="boolean", "default"=false}
]
response = "int"

[messages.get_measured]
doc = "Get most recent measured value. Additional key of measurement ID."

[messages.get_measured.response]
type = "map"
[[messages.get_measured.response.values]]
type = "float"

[[messages.get_measured.response.values]]
type = "record"
name = "ndarray"
logicalType = "ndarray"
[[messages.get_measured.response.values.fields]]
name = "shape"

[messages.get_measured.response.values.fields.type]
type = "array"
items = "int"
[[messages.get_measured.response.values.fields]]
name = "typestr"
type = "string"

[[messages.get_measured.response.values.fields]]
name = "data"
type = "bytes"

[[messages.get_measured.response.values.fields]]
name = "version"
type = "int"

[messages.stop_looping]
doc = "Stop looping measurement."

[messages.get_channel_names]
doc = "Get current channel names."
response.type = "array"
response.items = "string"

[messages.get_channel_shapes]
doc = "Get current channel shapes. If list is empty, channel is scalar."
response.type = "map"
response.values = {"type"="array", "items"="int"}

[messages.get_channel_units]
doc = "Get current channel units."
response.type = "map"
response.values = ["null", "string"]
