language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

# Installation installs dependencies
install:
  - pip install -r requirements.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python -E -Wall -tt -bb -m pytest tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then python -E -Wall -bb -m pytest tests; fi
# pypy doesn't like -tt option
