[tool.poetry]
name = "BeginnerPy"
version = "0.1.2"
description = ""
authors = ["Zech Zimmerman <hi@beginnerpy.com>"]

[tool.poetry.dependencies]
python = "^3.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
