#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['sonar']

package_data = \
{'': ['*'], 'sonar': ['mapping/*']}

install_requires = \
['tqdm']

entry_points = \
{'console_scripts': ['sonar = sonar.cli:main']}

setup(name='sonar',
      version='0.4.4',
      description='Sonar: Tool to profile usage of HPC resources by regularly probing processes',
      author='Radovan Bast',
      author_email='radovan.bast@uit.no',
      url='https://github.com/NordicHPC/sonar',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
     )
