# Generated by Django 3.0.6 on 2020-06-30 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0014_revenue_revenueitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='salary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue', to='labor.Salary'),
        ),
    ]
