[tool.poetry]
name = "excel2json-gui"
version = "0.1.0"
description = ""
authors = ["mflorczak"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt5 = "^5.15.0"
openpyxl = "^3.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
excel2json-gui = "excel2json_gui.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
