[tool.poetry]
name = "python-configuration"
version = "0.7.1"
description = "A library to load configuration parameters from multiple sources and formats"
authors = [
    "Tiago Requeijo <tiago.requeijo.dev@gmail.com>"
]
readme = 'README.md'
license = "MIT"
repository = "https://github.com/tr11/python-configuration"
homepage = "https://github.com/tr11/python-configuration"
keywords = ['configuration', 'settings', 'json', 'yaml', 'toml', 'ini']
packages = [
    { include = "config" },
]
include = ["config/py.typed"]

[tool.poetry.dependencies]
python = "^3.6"
pyyaml = {version = "^5.1", optional = true}
toml = {version = "^0.10.0", optional = true}
azure-keyvault = {version = "^4.0.0", optional = true}
azure-identity = {version = "^1.1.0", optional = true}
boto3 = {version = "^1.10.48", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.0"
pytest-cov = "^2.6"
pytest-flake8 = "^1.0"
mypy = "^0.730"
pytest-mypy = "^0.4.1"
flake8-docstrings = "^1.3"
flake8-comprehensions = "^2.0"
flake8-import-order = "^0.18.0"
flake8-bugbear = "^19.0"
flake8-blind-except = "^0.1.1"
flake8-builtins = "^1.4"
sphinx = "^2.1"
sphinx-autodoc-typehints = "^1.6"
pydocstyle = "^4.0"
pytest-black = "^0.3.7"
pytest-mock = "^2.0.0"
# need to allow pre-releases to address a recent change in pytest-black. See https://github.com/shopkeep/pytest-black/issues/45
black = { version = "*", allow-prereleases = true }

[tool.poetry.extras]
yaml = ["pyyaml"]
toml = ["toml"]
azure = ["azure-keyvault", "azure-identity"]
aws = ["boto3"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py36, py37, py38

[testenv]
whitelist_externals = poetry
commands =
    poetry install -v -E toml -E yaml -E azure -E aws
    poetry run pytest
"""

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
