[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "nbparameterise"
author = "Thomas Kluyver"
author-email = "thomas@kluyver.me.uk"
home-page = "https://github.com/takluyver/nbparameterise"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Framework :: Jupyter",
]
description-file = "README.rst"
requires = ["nbconvert", "astsearch"]
requires-python = ">=3.6"

