#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['nbparameterise', 'nbparameterise.code_drivers']

package_data = \
{'': ['*']}

install_requires = \
['nbconvert', 'astsearch']

setup(name='nbparameterise',
      version='0.4',
      description='Re-run a notebook substituting input parameters in the first cell.',
      author='Thomas Kluyver',
      author_email='thomas@kluyver.me.uk',
      url='https://github.com/takluyver/nbparameterise',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.6',
     )
