# Generated by Django 2.1.7 on 2020-07-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200702_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='pai',
            new_name='modulo_pai',
        ),
        migrations.AlterModelTable(
            name='modulo',
            table='modulo',
        ),
    ]
