#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup


setup(name='binsmooth',
      version='0.1',
      description='binsmooth - Better Estimates from Binned Income Data.',
      author='Stephen Tierney',
      author_email='sjtrny@gmail.com',
      url='http://github.com/sjtrny/binsmooth',
      py_modules=['binsmooth'],
     )
