language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install pep517
- pip install .
- pip install codecov
script:
- pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: IhUJcewiX0z2zSLisnGSFOU53mYfelnR3YczY6smeWuO8ExltmpRWqdcEKhSBlt4NkjRBg2cGuquVc9IdI5s//TOGycvGyOCc00oPisvB3rG4KIRIAkCUfPHyQLmTIm7sjAlAD6akL8JNQW+mPolVUvfCwI5IBK3LvxJcBAMM6M/mgP1z2IhQ81kUWv7CYpquY/6XcOC3QTW7vjdEpiMrPBB7stG0i+2uBEIjOOD/teKronkmoy7wu25PKsAPn6ccfsZw3BSanXMLnW+OkO5mZHatBr884CSqvwszCBInnrYddTeIS0A9gaANt7lxme2tCAS325rwfliIa+bAZfQCf1jwmqjlWrga97m7OTzjirsonEc6y3Ypos85gXS8+R4dqMewXT6LDpX7tA0LKC5DzRk6k7xvuyREprkNE7zQ8Hy1SpGCSJgQ2lR9nSmoIM9k/ep7rxD0LQKWlMEuTRi94fqyFQYZy9ZCHIc+34bITKk9tT1Rabj1XBwQa5eh3udhMw1JjRRUAt8MPkFIm3C6z/x6nE7dbzK7VeRLo+vA9ptafwdqzKm9ytk2xfF4TUBXalBJyGwZQODd0Fb6qth0ee46d3c/7y5rhpYhMfm3bLXRfqCO4MtkTCjX2z5084yf5lPKn5f+80f9Zq9VUoxch3vRTmXkWrXvGdYSn0Xvhg=
  on:
    tags: true
  skip_existing: true
