name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Tox and any other packages
      run: pip install tox
    - name: Run tox using the version of Python in `PATH`
      run: tox -e py
    - name: Check that docs build successfully
      run: tox -e docs
    - name: Run code through linters
      run: tox -e linters
    - name: Check package structure
      run: |
        # For unknown reason twine is not installed although defined
        # in tox.ini / setup.py
        pip install twine
        tox -e packaging
