[tool.poetry]
name = "spectrumm"
version = "0.1.1"
description = "A small CLI utlity to plot audiofiles"
authors = ["David Huss <dh@atoav.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.19.0"
scipy = "^1.5.1"
matplotlib = "^3.2.2"
pydub = "^0.24.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
spectrumm = "spectrumm.cli:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

