# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cm_client
from cm_client.rest import ApiException
from cm_client.apis.audits_resource_api import AuditsResourceApi


class TestAuditsResourceApi(unittest.TestCase):
    """ AuditsResourceApi unit test stubs """

    def setUp(self):
        self.api = cm_client.apis.audits_resource_api.AuditsResourceApi()

    def tearDown(self):
        pass

    def test_read_audits(self):
        """
        Test case for read_audits

        Fetch audit events from Cloudera Manager (CM) and CM managed services like HDFS, HBase, Impala, Hive, and Sentry.
        """
        pass

    def test_stream_audits(self):
        """
        Test case for stream_audits

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
