# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cm_client
from cm_client.rest import ApiException
from cm_client.apis.snapshots_resource_api import SnapshotsResourceApi


class TestSnapshotsResourceApi(unittest.TestCase):
    """ SnapshotsResourceApi unit test stubs """

    def setUp(self):
        self.api = cm_client.apis.snapshots_resource_api.SnapshotsResourceApi()

    def tearDown(self):
        pass

    def test_create_policies(self):
        """
        Test case for create_policies

        Creates one or more snapshot policies.
        """
        pass

    def test_delete_policy(self):
        """
        Test case for delete_policy

        Deletes an existing snapshot policy.
        """
        pass

    def test_read_history(self):
        """
        Test case for read_history

        Returns a list of commands triggered by a snapshot policy.
        """
        pass

    def test_read_policies(self):
        """
        Test case for read_policies

        Returns information for all snapshot policies.
        """
        pass

    def test_read_policy(self):
        """
        Test case for read_policy

        Returns information for a specific snapshot policy.
        """
        pass

    def test_update_policy(self):
        """
        Test case for update_policy

        Updates an existing snapshot policy.
        """
        pass


if __name__ == '__main__':
    unittest.main()
