# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cm_client
from cm_client.rest import ApiException
from cm_client.models.api_time_series_cross_entity_metadata import ApiTimeSeriesCrossEntityMetadata


class TestApiTimeSeriesCrossEntityMetadata(unittest.TestCase):
    """ ApiTimeSeriesCrossEntityMetadata unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiTimeSeriesCrossEntityMetadata(self):
        """
        Test ApiTimeSeriesCrossEntityMetadata
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = cm_client.models.api_time_series_cross_entity_metadata.ApiTimeSeriesCrossEntityMetadata()
        pass


if __name__ == '__main__':
    unittest.main()
