# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cm_client
from cm_client.rest import ApiException
from cm_client.apis.mgmt_role_config_groups_resource_api import MgmtRoleConfigGroupsResourceApi


class TestMgmtRoleConfigGroupsResourceApi(unittest.TestCase):
    """ MgmtRoleConfigGroupsResourceApi unit test stubs """

    def setUp(self):
        self.api = cm_client.apis.mgmt_role_config_groups_resource_api.MgmtRoleConfigGroupsResourceApi()

    def tearDown(self):
        pass

    def test_read_config(self):
        """
        Test case for read_config

        Returns the current revision of the config for the specified role config group in the Cloudera Management Services.
        """
        pass

    def test_read_role_config_group(self):
        """
        Test case for read_role_config_group

        Returns the information for a given role config group in the Cloudera Management Services.
        """
        pass

    def test_read_role_config_groups(self):
        """
        Test case for read_role_config_groups

        Returns the information for all role config groups in the Cloudera Management Services.
        """
        pass

    def test_read_roles(self):
        """
        Test case for read_roles

        Returns all roles in the given role config group in the Cloudera Management Services.
        """
        pass

    def test_update_config(self):
        """
        Test case for update_config

        Updates the config for the given role config group in the Cloudera Management Services.
        """
        pass

    def test_update_role_config_group(self):
        """
        Test case for update_role_config_group

        Updates an existing role config group in the Cloudera Management Services.
        """
        pass


if __name__ == '__main__':
    unittest.main()
