# coding: utf-8

"""
    Cloudera Manager API

    <h1>Cloudera Manager API v41</h1>       <p>Introduced in Cloudera Manager 7.1.1</p>       <p><a href=\"http://www.cloudera.com/documentation.html\">Cloudera Product Documentation</a></p>

    OpenAPI spec version: 7.1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import cm_client
from cm_client.rest import ApiException
from cm_client.apis.external_user_mappings_resource_api import ExternalUserMappingsResourceApi


class TestExternalUserMappingsResourceApi(unittest.TestCase):
    """ ExternalUserMappingsResourceApi unit test stubs """

    def setUp(self):
        self.api = cm_client.apis.external_user_mappings_resource_api.ExternalUserMappingsResourceApi()

    def tearDown(self):
        pass

    def test_create_external_user_mappings(self):
        """
        Test case for create_external_user_mappings

        Creates a list of external user mappings.
        """
        pass

    def test_delete_external_user_mapping(self):
        """
        Test case for delete_external_user_mapping

        Deletes an external user mapping from the system.
        """
        pass

    def test_read_external_user_mapping(self):
        """
        Test case for read_external_user_mapping

        Returns detailed information about an external user mapping.
        """
        pass

    def test_read_external_user_mappings(self):
        """
        Test case for read_external_user_mappings

        Returns a list of the external user mappings configured in the system.
        """
        pass

    def test_update_external_user_mapping(self):
        """
        Test case for update_external_user_mapping

        Updates the given external user mapping's information.
        """
        pass


if __name__ == '__main__':
    unittest.main()
