- project:
    templates:
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-train-jobs
      - openstacksdk-functional-tips
      - openstacksdk-tox-tips
      - osc-tox-unit-tips
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
