# Generated by Django 3.0.6 on 2020-06-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200619_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='classification',
            field=models.CharField(blank=True, choices=[('individual', 'Egyéni vállalkozás'), ('organization', 'Társas vállalkozás')], default='organization', max_length=100, null=True, verbose_name='típus'),
        ),
    ]
