[tool.poetry]
name = "awsglue-local"
version = "1.0.2"
description = "Build Python interfaces to the AWS Glue ETL library for use as a local dependency."
authors = ["Ryan Eloff <ryan.peter.eloff@gmail.com>"]
packages = [
    { include = "awsglue" },
]
license = "Amazon Software License 1.0"
readme = "awsglue/README.md"
repository = "https://github.com/rpeloff/aws-glue-libs/tree/glue-1.0"

[tool.poetry.dependencies]
python = "^3, < 3.8"
pyspark = "^2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
