[tool.poetry]
name = "cleaner-py"
packages = [
    {include = "cleaner"}
]
version = "0.1.0"
description = ""
authors = ["Schumi543 <12729148+Schumi543@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
cleo = "^0.8.1"
clikit = "^0.6.2"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"
freezegun = "^0.3.15"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
