# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-27 14:59
from __future__ import unicode_literals

import dj_utils.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonData',
            fields=[
                ('id', models.CharField(default=dj_utils.models.unique_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('json_data', models.TextField(blank=True)),
                ('data_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
