language: python
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
  - pip install zc.buildout
  - sed -ie "s#5.2.x.cfg#$PLONE_VERSION.cfg#" buildout.cfg
install:
  - buildout -N annotate
  - buildout -N
before_script:
  - sleep 3
script:
# Run code-analysis, except on Python 3.6, which mysteriously fails to find zc.buildout.
  - python --version 2> /dev/stdout | grep 3.6 || bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage -t "--layer=!Robot" -d htmlcov
  - pip install --upgrade coveralls
  - coveralls
notifications:
  irc: irc.freenode.org#plone-testing
