# Generated by Django 2.1.7 on 2020-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='ist_login',
            new_name='is_login',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='ist_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='grupouser',
            old_name='ist_admin',
            new_name='is_admin',
        ),
        migrations.RemoveField(
            model_name='grupologin',
            name='sistema',
        ),
        migrations.RemoveField(
            model_name='pontofuncao',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='pontofuncao',
            name='pagina',
        ),
        migrations.RemoveField(
            model_name='pontofuncao',
            name='sistema',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
