[tool.poetry]
name = "calixa-proto-py"
version = "0.1.0"
description = ""
authors = ["Calixa  Platform <everyone@calixa.io>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[tool.poetry.scripts]
copy-py-proto-script = "copy_generated_py_proto:start"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
