[tool.poetry]
name = "pay-by-square"
version = "0.2.0"
description = "Generate QR codes for by square payments"
authors = ["Matúš Ferech"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/matusf/pay-by-square"
keywords = ["payments", "qrcode", "pay", "by-square", "pay-by-square"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
