# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AgentFeedBack.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AgentFeedBack.proto',
  package='grpc.cmp.proxy.api.agent',
  syntax='proto3',
  serialized_options=b'P\001',
  serialized_pb=b'\n\x13\x41gentFeedBack.proto\x12\x18grpc.cmp.proxy.api.agent\"\x80\x02\n\x0b\x46\x65\x65\x64\x62\x61\x63kLog\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ncreateTime\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x65p\x18\x03 \x01(\t\x12\x12\n\nserverName\x18\x04 \x01(\t\x12\x0e\n\x06\x64omain\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x0f\n\x07proxyIP\x18\x07 \x01(\t\x12\x10\n\x08\x63ostTime\x18\x08 \x01(\x05\x12\x0e\n\x06statue\x18\t \x01(\x05\x12\x10\n\x08provider\x18\n \x01(\t\x12\x11\n\tproxyType\x18\x0b \x01(\t\x12\x11\n\texception\x18\x0c \x01(\t\x12\x14\n\x0cresponseSize\x18\r \x01(\x05\x12\x12\n\nreportTime\x18\x0e \x01(\x03\" \n\rFeedbackReply\x12\x0f\n\x07message\x18\x01 \x01(\t2r\n\x14\x41gentFeedbackService\x12Z\n\x08\x66\x65\x65\x64\x62\x61\x63k\x12%.grpc.cmp.proxy.api.agent.FeedbackLog\x1a\'.grpc.cmp.proxy.api.agent.FeedbackReplyB\x02P\x01\x62\x06proto3'
)




_FEEDBACKLOG = _descriptor.Descriptor(
  name='FeedbackLog',
  full_name='grpc.cmp.proxy.api.agent.FeedbackLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='createTime', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.createTime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dep', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.dep', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverName', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.serverName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='domain', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.domain', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='url', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proxyIP', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.proxyIP', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='costTime', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.costTime', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='statue', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.statue', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='provider', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.provider', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='proxyType', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.proxyType', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exception', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.exception', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='responseSize', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.responseSize', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reportTime', full_name='grpc.cmp.proxy.api.agent.FeedbackLog.reportTime', index=13,
      number=14, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=306,
)


_FEEDBACKREPLY = _descriptor.Descriptor(
  name='FeedbackReply',
  full_name='grpc.cmp.proxy.api.agent.FeedbackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='grpc.cmp.proxy.api.agent.FeedbackReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=340,
)

DESCRIPTOR.message_types_by_name['FeedbackLog'] = _FEEDBACKLOG
DESCRIPTOR.message_types_by_name['FeedbackReply'] = _FEEDBACKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeedbackLog = _reflection.GeneratedProtocolMessageType('FeedbackLog', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACKLOG,
  '__module__' : 'AgentFeedBack_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cmp.proxy.api.agent.FeedbackLog)
  })
_sym_db.RegisterMessage(FeedbackLog)

FeedbackReply = _reflection.GeneratedProtocolMessageType('FeedbackReply', (_message.Message,), {
  'DESCRIPTOR' : _FEEDBACKREPLY,
  '__module__' : 'AgentFeedBack_pb2'
  # @@protoc_insertion_point(class_scope:grpc.cmp.proxy.api.agent.FeedbackReply)
  })
_sym_db.RegisterMessage(FeedbackReply)


DESCRIPTOR._options = None

_AGENTFEEDBACKSERVICE = _descriptor.ServiceDescriptor(
  name='AgentFeedbackService',
  full_name='grpc.cmp.proxy.api.agent.AgentFeedbackService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=342,
  serialized_end=456,
  methods=[
  _descriptor.MethodDescriptor(
    name='feedback',
    full_name='grpc.cmp.proxy.api.agent.AgentFeedbackService.feedback',
    index=0,
    containing_service=None,
    input_type=_FEEDBACKLOG,
    output_type=_FEEDBACKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AGENTFEEDBACKSERVICE)

DESCRIPTOR.services_by_name['AgentFeedbackService'] = _AGENTFEEDBACKSERVICE

# @@protoc_insertion_point(module_scope)
