
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

# pylint: disable=C0103

import json

version_json = '''
{
 "date": "2020-06-18T22:58:24+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "466daa86cf78dd643c53d1996eea3759587733bf",
 "version": "1.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
