tsana_app_name: demomodeless
tsana_api_key: 335cbcd9-b141-4e5a-9b88-d1283a9a0e3f
tsana_api_endpoint: https://stock-exp2-api.azurewebsites.net
series_limit: 5000000
models_in_training_limit_per_instance: 1
az_tsana_meta_table: modelmeta
az_tsana_moniter_table: moniter
model_temp_dir: temp
model_data_dir: data
training_owner_life: 60