[tool.poetry]
name = "threader3000"
version = "0.1.7"
description = "Threader3000 - Multi-threaded Port Scanner"
authors = ["The Mayor"]
readme = "README.md"

[tool.poetry.scripts]
threader3000 = 'threader3000:main'

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
