repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: ['--line-length', '120']
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.780'  # Use the sha / tag you want to point at
    hooks:
    - id: mypy
      args: ['--config-file', 'mypy.ini']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    - id: flake8
      args: ['--config', 'flake8.cfg']
      additional_dependencies:
        - isort<5  # https://github.com/gforcada/flake8-isort/issues/88