[tool.poetry]
name = "keepy"
version = "0.0.1a0"
description = "A Python Keepass CLI utility (placeholder package)"
authors = ["Patryk Tech <git@patryk.tech>"]

[tool.poetry.dependencies]
python = "^3.8"
pykeepass = "^3.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
