[tool]
[tool.poetry]
name = "b5"
version = "1.1.9"
description = "b5 - simple and sane task runner"
authors = ["David Danier <danier@team23.de>"]
maintainers = ["David Danier <danier@team23.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/team23/b5"
repository = "https://github.com/team23/b5"
documentation = "https://github.com/team23/b5/tree/master/docs"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Intended Audience :: System Administrators',
    'License :: OSI Approved :: BSD License',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Unix',
    'Operating System :: POSIX',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3 :: Only',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Topic :: Software Development',
    'Topic :: Software Development :: Build Tools',
    'Topic :: System :: Systems Administration',
]

[tool.poetry.dependencies]
python = ">=3.4"
jinja2 = "==2.*,>=2.10.0"
markupsafe = "==1.*,>=1.1.0"
packaging = ">=16.0"
pyyaml = "==5.*,>=5.1.0"
termcolor = "==1.1.*,>=1.1.0"

[tool.poetry.dev-dependencies]
pylint = ">=2.3.1"
pytest = ">=5.3.2"

[tool.poetry.scripts]
b5 = 'b5.main:main'
b5-init = 'b5.init:main'
b5-execute = 'b5.execute:main'

#[build-system]
#requires = ["poetry>=0.12"]
#build-backend = "poetry.masonry.api"
