[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "forecastvh"
author = "Ilia Fedorovich"
description-file = "README.md"
requires-python = ">=3.8"
author-email = "workplaceilfed@gmail.com"
home-page = "https://github.com/MorningStar-png/weathervh-py"
classifiers = [
	"License :: OSI Approved :: MIT License",
	"Programming Language :: Python :: 3",
	]

