[tool.poetry]
name = "ca-bundle"
version = "0.1.1"
description = "No more SSL errors because of unset REQUESTS_CA_BUNDLE."
authors = ["Matúš Ferech"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/matusf/ca-bundle/"
keywords = ["ssl", "ca-certificates", "requests"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
