[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "velin"
author = "Matthias Bussonnier"
author-email = "bussonniermatthias@gmail.com"
home-page = "https://github.com/Carreau/velin"
classifiers = ["License :: OSI Approved :: MIT License"]

[tool.flit.scripts]
velin = "velin:main"
