name: Milestone Closure

on:
  milestone:
    types: [closed]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "sv-tools-bot"
          git config user.email "sv.go.tools@gmail.com"
          git fetch --all
      - name: Create Tag
        run: |
          docker pull svtools/bumptag:latest
          docker run --rm -v $PWD:/mount -w /mount svtools/bumptag:latest ${{ github.event.milestone.title }}
      - name: Push Tag
        run: git push origin --tags
