class KERR:
    WEBSOCKET_ERR=100
    SERIAL_COMM_ERROR=101
    CANNOT_FIND_DISK=102
    UPLOAD_IMAGE_FAIL=103


    UPLOAD_FIRM_FAIL=110
    CANNOT_FIND_COMMPORT=170
    CANNOT_FIND_COMMPORT_BUTDISK=171
    DISK_IN_BOOTLOADER_MODE=172
    DRIVER_INSTALL_FAIL = 180
    DRIVER_INSTALL_DOWNLOADFAIL = 181
    DRIVER_INSTALL_OSX = 183


