[tool.poetry]
name = "vartoml"
version = "0.9.5"
description = "Enable variables in a TOML file"
authors = ["Manfred Lotz <manfred.lotz@posteo.de>"]
license = "MIT"
repository = "https://github.com/manfredlotz/vartoml"

[tool.poetry.dependencies]
python = ">= 3.5"
toml = ">= 0.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
