
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-06T17:45:31+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2ca80b3912f009f8c510fdf1f770f41d3dfc090",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
