[tool.poetry]
name = "appchen"
version = "0.3.0"
description = "A client/server web framework based an Python and modern JavaScript."
authors = ["Wolfgang Kühn"]
homepage = "https://github.com/decatur/app-chen"
repository = "https://github.com/decatur/app-chen"
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1"
pymongo = "^3.10"
sseclient = "^0.0.24"
requests  = "^2.23.0"
