
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-10T13:12:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "53f19255c4391484c746e4a303f82ccd9ac6b643",
 "version": "0.13.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
