[build-system]
requires = [ "setuptools >= 35.0.2", "wheel >= 0.29.0", "twine", "cython == 0.29.6" ]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 110
target-version = ['py36', 'py37', 'py38']
