[tool.poetry]
name = "healpix-alchemy"
version = "0.0.1"
description = "SQLAlchemy extensions for HEALPix spatially indexed astronomy data"
authors = ["Leo Singer <leo.singer@ligo.org>"]
license = "BSD-3-clause"
repository = "https://github.com/skyportal/healpix-alchemy"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Topic :: Database",
    "Topic :: Scientific/Engineering :: Astronomy"
]

[tool.poetry.dependencies]
python = "^3.7"
sqlalchemy = "*"
astropy = "*"

[tool.poetry.dev-dependencies]
numpy = "*"
psycopg2-binary = "*"
pytest = "*"
pytest-benchmark = "*"
pytest-postgresql = "*"
scipy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
