#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['libusbmuxd']

package_data = \
{'': ['*']}

setup(name='libusbmuxd',
      version='0.1',
      description='Python bindings for libusbmuxd',
      author='Rick Mark',
      author_email='rickmark@guardianapp.com',
      url='https://github.com/libimobiledevice/python-libusbmuxd',
      packages=packages,
      package_data=package_data,
     )
