
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-13T18:27:14+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "a411024fd6d90d15e63f1e0ff10f30caa85fe741",
 "version": "1.2.3-alpha.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
