[tool.poetry]
name = "benpkg"
version = "0.4.0"
description = "some package"
authors = ["Ben-Cheng <bcheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.6"
pyqt5 = "^5.10"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
