[tool.poetry]
name = "file-path-cli"
version = "0.1.5"
description = ""
authors = ["Eyal Levin <eyalev@gmail.com>"]
repository = 'https://github.com/eyalev/file-path-cli'
readme = "README.md"

[tool.poetry.scripts]
file-path = "file_path_cli.cli:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.2"
pyperclip = "^1.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^19.10b0", allow-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
