# Generated by Django 3.0.6 on 2020-06-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'ügyfél', 'verbose_name_plural': 'ügyfelek'},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
