image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - tests
  - system test
  - release

pytest:
  stage: tests
  script:
    - python3 -m pip install -r setup/requirements/requirements.txt
    - python3 -m pip install -r setup/requirements/dev-requirements.txt
    - cd wizer/tests/
    - python3 -m pytest unit_tests -v
    - python3 -m pytest integration_tests -v

django:
  stage: tests
  artifacts:
    paths:
      - db.sqlite3
    expire_in: 1 day
  script:
    - python3 -m pip install -r setup/requirements/requirements.txt
    - python3 manage.py collectstatic --noinput
    - python3 manage.py check
    - python3 manage.py migrate

end2end:
  stage: system test
  script:
    - python3 -m pip install -r setup/requirements/requirements.txt
    - python3 -m pip install -r setup/requirements/dev-requirements.txt
    - python3 -m pytest wizer/tests/end2end/end2end.py -vvs

pypi:
  stage: release
  cache: {}
  script:
    - pip install -U twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - master
  only:
    - tags
