[tool.poetry]
name = "snowday"
version = "0.1.1"
description = "Tools for turning Snowflake into a Snow Day. ❄️"
authors = ["Jacob Thomas <jake@bostata.com>"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/bostata/snowday"
repository = "https://github.com/bostata/snowday"
keywords = ["snowflake", "data warehouse", "snow"]
classifiers = [
    "Environment :: Console",
    "Framework :: Flake8",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Documentation",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
