[tool.poetry]
name = "meldtools"
version = "0.2.0"
description = "Tools used to work with MELD texts"
authors = ["Michał Adamczyk <michal.adamczyk.1990@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.5"
pandasql = "^0.7.3"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
mypy = "^0.780"
pytest = "^5.4.3"
jedi = "^0.17.0"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.9.0"

[tool.coverage.paths]
source = ["meldtools", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["meldtools"]

[tool.coverage.report]
show_missing = true

[tool.poetry.scripts]
meldtools = "meldtools.__main__:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
