
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-06T17:17:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb2420c27fee82a38069dcda42403419bc522d18",
 "version": "0.8.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
