environment:
  matrix:
#    - PYTHON: "C:\\Python27-x64"
#      PYTHON_VERSION: "2.7.14"
#      PYTHON_ARCH: "64"
    
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "64"

install:
  # use the version of python to test, instead of
  # the default (currently 2.7)
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build_script:
  - "c:\\python36-x64\\python.exe -m pip install --upgrade pip"
  - "pip install -r requirements-test.txt"
  - "pip install -r requirements.txt"
  - "python setup.py build"

test_script:
- "python setup.py test"