[tool.poetry]
name = "crypto-candlesticks"
version = "0.1.2"
description = "Download candlestick data fast & easy for analysis"
authors = ["Pedro Torres <corfucinas@protonmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://crypto-candlesticks.readthedocs.io/en/latest/"
repository = "https://github.com/Corfucinas/crypto-candlesticks"
keywords = ["cryptocurrency", "candlesticks", "download", "data", "ohlc"]

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.0.5"
numpy = "^1.19.0"
requests = "^2.24.0"
click = "^7.1.2"
retry = "^0.9.2"
tqdm = "^4.47.0"
importlib_metadata = {version = "^1.7.0", python = "<3.8"}

[tool.poetry.dev-dependencies]
black = "^19.10b0"
mypy = "^0.782"
sphinx = "^3.1.1"
pytest = "^5.4.3"
coverage = {extras = ["toml"], version = "^5.1"}
pytest-cov = "^2.10.0"
pytest-mock = "^3.1.1"
sphinx-autodoc-typehints = "^1.11.0"
nox = "^2020.5.24"
flake8-annotations = "^2.1.0"
flake8-bandit = "^2.1.2"
flake8-black = "^0.2.0"
flake8-docstrings = "^1.5.0"
safety = "^1.9.0"
darglint = "^1.4.1"
xdoctest = "^0.12.0"
sphinx_autodoc_typehints = "^1.11.0"
isort = "^5.0.3"
pre-commit = "^2.6.0"
codecov = "^2.1.7"
colorama = "^0.4.3"
pygments = "^2.6.1"
wemake-python-styleguide = "^0.14.0"

[tool.black]
line-length = 79
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["crypto_candlesticks"]

[tool.coverage.report]
show_missing = true

[tool.poetry.scripts]
crypto-candlesticks = "crypto_candlesticks.interface:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
