# Generated by Django 2.1.15 on 2020-06-16 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedb.Database'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('database', 'name')},
        ),
    ]
