[tool.poetry]
name = "anyflow"
version = "0.1.1"
description = "a simplest common middleware framework for python."
authors = ["Cologler <skyoflw@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.4.3"

[tool.poetry-dynamic-versioning]
enable = true
format = '{base}'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

