[tool.poetry]
name = "aiopen"
version = "0.0.1"
description = ""
authors = ["sheldon-turtle <sheldon@dgi.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

### CLI
#[tool.poetry.scripts]
#<CMD> = "dgpy_pkg.cli:main"
