[tool.poetry]
name = "s3tar"
version = "1.4.1"
description = "Pulls (filtered) files from S3 and adds them to a tar archive."
authors = ["Chris Allison <chris.charles.allison+s3tar@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/ccdale/s3tar"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.1.1"
ccaaws = "^0.4.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
star = "s3tar.star:star"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
