version: 2.1

jobs:
  build:
    docker:
      - image: deltachat/pymailserver 
    steps:
      - checkout
      - run: 
          name: tox-test mailadm 
          environment: 
                LC_ALL: C.UTF-8
                LANG: C.UTF-8
          command: |
            tox 
