{% include "default_menubar.yml" %}

vcp:
  name: Not Set
  version: Not Set
  author: Not Set
  description: No description provided.

windows:
  mainwindow:
    provider: qtpyvcp.widgets.form_widgets.main_window:VCPMainWindow

# This sections defines the default Data Sources
data_plugins:
  status:
    provider: qtpyvcp.plugins.status:Status
    kwargs:
      cycle_time: 75

  persistent_data_manager:
    provider: qtpyvcp.plugins.persistent_data_manager:PersistentDataManager
    kwargs:
      # serialization method to use: json or pickle
      serialization_method: pickle
      # persistence_file: .vcp_data.json

  settings:
    provider: qtpyvcp.plugins.settings:Settings

  position:
    provider: qtpyvcp.plugins.positions:Position
    kwargs:
      report_actual_pos: True
      use_program_units: True

  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable

  notifications:
    provider: qtpyvcp.plugins.notifications:Notifications
    kwargs:
      # show notification popups
      enabled: True
      # "native" or "dbus"
      mode: native
      # max number of notifications to show
      max_messages: 5
      # whether to save messages on exit
      persistent: True

  file_locations:
    provider: qtpyvcp.plugins.file_locations:FileLocations
    log_level: debug
    kwargs:
      default_location: NC Files
      local_locations:
        # format: Location Name: path
        Home: ~/
        Desktop: ~/Desktop
        NC Files: ~/linuxcnc/nc_files
      network_locations:

    exportedhal:
        provider: qtpyvcp.plugins.exported_hal:ExportedHal

dialogs:
  open_file:
    provider: qtpyvcp.widgets.dialogs.open_file_dialog:OpenFileDialog

  set_work_offsets:
    provider: qtpyvcp.widgets.dialogs.offsets_dialog:OffsetsDialog

  tool_edit:
    provider: qtpyvcp.widgets.dialogs.base_dialog:BaseDialog
    kwargs:
      ui_file: {{ file.dir }}/../widgets/dialogs/tooledit_dialog.ui

  probe_sim:
    provider: qtpyvcp.widgets.dialogs.probesim_dialog:ProbeSim

  about_qtpyvcp:
    provider: qtpyvcp.widgets.dialogs.about_dialog:AboutDialog

virtual_keyboards:
  default:
    provider: qtpyvcp.ui_vkb_loader.UIVKBLoader
    args: []
    kwargs:
      ui_file: keyboards/default_vkb.ui

  integer:
    provider: qtpyvcp.ui_vkb_loader.UIVKBLoader
    args: []
    kwargs:
      ui_file: keyboards/integer_vkb.ui
      frameless: True
      modal: False

application:
  provider: qtpyvcp.app.application:VCPApplication
  kwargs:
#    stylesheet: {{ file.dir }}/widgets/default_stylesheet.qss   # application wide stylesheet

settings:
  touch-probe.diameter-offset:
    default_value: 0.0
    persistent: true
    min_value: 0
    max_value: 1

  dro.display-units:
    default_value: 0
#    options: [Program, Inch, Metric]

  dro.inch-format:
    default_value: '%9.4f'
    value_type: str

  dro.millimeter-format:
    default_value: '%9.3f'
    value_type: str

  dro.degree-format:
    default_value: '%9.2f'
