[tool.poetry]
name = "html-diff"
version = "0.3.0"
description = "HTML-formatted diff'ing of HTML snippets"
license = "AGPL-3.0+"
authors = ["Quentin Wenger <quentin.wenger@oly-exams.org>"]
readme = "README.md"
homepage = "https://gitlab.com/matpi/html-diff"
repository = "https://gitlab.com/matpi/html-diff"
keywords = ["html", "diff"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Environment :: Web Environment",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.5",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development",
    "Topic :: Text Processing :: Markup :: HTML",
]

[tool.poetry.dependencies]
python = "^3.5"
beautifulsoup4 = "^4.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
