# Generated by Django 3.0.6 on 2020-06-19 00:44

import address.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Nő'), ('male', 'Férfi')], default=None, max_length=10, null=True, verbose_name='nem')),
                ('birthdate', models.DateField(verbose_name='születési dátum')),
                ('birthplace', models.CharField(max_length=200, verbose_name='születési hely')),
                ('name_of_mother', models.CharField(default=None, max_length=200, verbose_name='anyja neve')),
                ('first_name', models.CharField(max_length=100, verbose_name='keresztnév')),
                ('middle_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='középső név')),
                ('last_name', models.CharField(max_length=100, verbose_name='családnév')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='telefonszám')),
                ('email', models.EmailField(max_length=254, verbose_name='email cím')),
                ('nationality', models.CharField(max_length=100, verbose_name='nemzetiség')),
                ('inland_resident', models.BooleanField(default=True, help_text='Rendelkezik belföldi lakcímmel.', verbose_name='belföldi lakcím')),
                ('tax_number', models.CharField(max_length=100, verbose_name='adó azonosító jel')),
                ('permanent_address', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_residents', to='address.Address', verbose_name='állandó lakcím')),
                ('temporary_address', address.models.AddressField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termorary_residents', to='address.Address', verbose_name='ideiglenes lakcím')),
            ],
            options={
                'verbose_name': 'személy',
                'verbose_name_plural': 'személyek',
                'db_table': 'persons',
            },
        ),
    ]
