[tool.poetry]
name = "pyside2-utils"
version = "0.0.1"
description = "PySide2 utilities."
authors = ["MadaRa <zaurik777to@gmail.com>"]

[tool.poetry.dependencies]
python = "3.7"
pyside2 = "^5.15.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pylint = "^2.5.3"
mypy = "^0.782"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
