# Generated by Django 2.1.7 on 2020-07-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0002_auto_20200702_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filial',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='filialservico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'managed': False},
        ),
    ]
