[tool.poetry]
name = "demoben"
version = "0.1.1"
description = ""
authors = ["Ben-Cheng <bcheng@linz.govt.nz>"]

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]
pytest = "^4.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
