[tool.poetry]
name = "infernal"
version = "0.0.0"
description = "Core library for the Infernal eSports Analytics Infernal library."
authors = ["Shparki <murrmat@gmail.com>"]
packages = [
    { include = "infernal" }
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
selenium = "^3.141.0"
vaex = "^3.0.0"

[tool.poetry.dev-dependencies]
numpy = "^1.18.2"
pytest = "^5.3.5"
pylint = "^2.4.4"
pandas = "^1.0.3"
jupyter = "^1.0.0"
pydocstyle = "^5.0.2"
beautifulsoup4 = "^4.9.0"
Pillow = "^7.1.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
