# Generated by Django 2.2 on 2020-07-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocomment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('DEACTIVE', 'deactive')], default='ACTIVE', max_length=8),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
