
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-03T22:07:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "9928a72b6643f27e64a7fa8581196ee593c0f5f2",
 "version": "v0.9.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
